name: Rename project from template

on: [ push ]

jobs:
  rename:
    if: ${{ github.repository	!= 'rmenai/python-structure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0

      - name: Rename the project
        run: |
          echo "Renaming the project with -a ${{ github.repository_owner }} -n ${{ github.event.repository.name }}"
          bash .github/temp/rename_project.sh -a ${{ github.repository_owner }} -n ${{ github.event.repository.name }} -d "Awesome ${{ github.event.repository.name }} created by ${{ github.repository_owner }}"

      - name: Delete temp files
        run: |
          rm -r .github/temp
          rm .github/workflows/rename.yaml

      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "::set-output name=msg::$(git log -1 --pretty=%s)"

      - name: Push new commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_options: '--amend --no-edit'
          push_options: --force
